#!/usr/bin/env node
/**
 * Build crates/core → packages/core/pkg (wasm-pack, web target).
 *
 * Windows + non-ASCII username: run via
 *   powershell -File scripts/env-rust-windows.ps1; node scripts/build-wasm.mjs
 * or set RUSTUP_HOME=C:\Rust\rustup first (see scripts/env-rust-windows.ps1).
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const crate = join(root, 'crates', 'core');
const outDir = join(root, 'packages', 'core', 'pkg');

function run(cmd, args) {
  const r = spawnSync(cmd, args, {
    stdio: 'inherit',
    shell: true,
    cwd: root,
    env: process.env,
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}

function onPath(bin) {
  const r = spawnSync(process.platform === 'win32' ? 'where' : 'which', [bin], {
    encoding: 'utf8',
    shell: true,
  });
  return r.status === 0 && Boolean(r.stdout?.trim());
}

if (process.platform === 'win32' && !process.env.RUSTUP_HOME) {
  const ascii = 'C:\\Rust\\rustup';
  if (existsSync(join(ascii, 'toolchains'))) {
    process.env.RUSTUP_HOME = ascii;
    console.log('Using RUSTUP_HOME=' + ascii);
  } else {
    console.warn(
      'Hint: non-ASCII Windows usernames break mingw ld. Run scripts/env-rust-windows.ps1 once.'
    );
  }
}

if (!onPath('wasm-pack')) {
  console.error('wasm-pack not found. https://rustwasm.github.io/wasm-pack/installer/');
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

run('wasm-pack', [
  'build',
  crate,
  '--target',
  'web',
  '--out-dir',
  outDir,
  '--out-name',
  'web_ffmpeg_core',
  '--release',
]);

writeFileSync(
  join(outDir, 'index.js'),
  `/* auto-generated by scripts/build-wasm.mjs */
export * from './web_ffmpeg_core.js';
export { default } from './web_ffmpeg_core.js';
`
);

// wasm-pack emits `pkg/.gitignore` with `*` — keep artifacts usable in-repo.
writeFileSync(
  join(outDir, '.gitignore'),
  ['# kept by scripts/build-wasm.mjs', '.*', '!.gitignore', ''].join('\n')
);

console.log('OK: Rust WASM →', outDir);
